provider/azure: Randomize DNS Server acctest names
This commit should fix the following acceptance test failures:

=== RUN   TestAccAzureDnsServerBasic
--- FAIL: TestAccAzureDnsServerBasic (2.17s)
	testing.go:172: Step 0 error: Error applying: 1 error(s) occurred:

        * azure_dns_server.foo: Failed issuing update to network
          configuration: Error response from Azure. Code: BadRequest,
          Message: Multiple DNS servers specified with the same name
          'terraform-dns-server'.
=== RUN   TestAccAzureDnsServerUpdate
--- FAIL: TestAccAzureDnsServerUpdate (2.04s)
        testing.go:172: Step 0 error: Error applying: 1 error(s) occurred:

        * azure_dns_server.foo: Failed issuing update to network
          configuration: Error response from Azure. Code: BadRequest,
          Message: Multiple DNS servers specified with the same name
          'terraform-dns-server'.